name: release

on:
  workflow_dispatch:
    inputs:
      deploy_cw:
        description: "Deploy ClaimerWeb"
        required: true
        default: "true"
        type: boolean
      deploy_bg:
        description: "Deploy Background"
        required: true
        default: "true"
        type: boolean
      deploy_is:
        description: "Deploy Issuer"
        required: true
        default: "true"
        type: boolean

      version:
        description: "Version Increment"
        required: true
        default: "patch"
        type: choice
        options:
        - patch
        - minor
        - major 

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    name: 'Deploy Release'
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.12.3' # Define the elixir version [required]
          otp-version: '24.1' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Increment version
        id: increment_version
        run: echo "::set-output name=app_version::$(mix increment_version ${{ github.event.inputs.version }})"

      - name: publish commit
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add VERSION
          git commit -m "released revision ${{ steps.increment_version.outputs.app_version }}"
          git push gh-origin $GITHUB_REF --tags
      - name: Deploy Background
        if: github.event.inputs.deploy_bg == 'true'
        id: deploy-asg-bg
        run: echo "deploying background"
      - name: Deploy Issuer
        if: github.event.inputs.deploy_is == 'true'
        id: deploy-asg-is
        run: echo "deploying issuer"
      - name: Deploy ClaimerWeb
        if: github.event.inputs.deploy_cw == 'true'
        id: deploy-asg-cw
        run: echo "deploying ClaimerWeb"